### ISSUE TITLE
"Getting Started" Instructions not working for Centos stream 8

### ISSUE THREAD

**Issue by DonMaEn** [ICESat2-SlideRule/sliderule-python#118]
While following the [Getting Started instruction](http://icesat2sliderule.org/gettingstarted/) I encountered an error. Specifically, the first processing request step 2 is what gave me the error

The error I get is initially
```
>>> icesat2.init("icesat2sliderule.org", verbose=True)
WARNING:sliderule.sliderule:Failed to retrieve username and password from netrc file: 'ps.icesat2sliderule.org'
```

Then several other errors that all give the message:

```
During handling of the above exception, another exception occurred:
```

Followed by a final error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dsm2588/Projects/Git-Repos/sliderule-python/sliderule/icesat2.py", line 527, in init
    sliderule.check_version(plugins=['icesat2'])
  File "/home/dsm2588/Projects/Git-Repos/sliderule-python/sliderule/sliderule.py", line 769, in check_version
    info = get_version()
  File "/home/dsm2588/Projects/Git-Repos/sliderule-python/sliderule/sliderule.py", line 747, in get_version
    rsps = source("version", {})
  File "/home/dsm2588/Projects/Git-Repos/sliderule-python/sliderule/sliderule.py", line 446, in source
    raise FatalError("Failed to connect to endpoint {}".format(url))
sliderule.sliderule.FatalError: Failed to connect to endpoint https://sliderule.icesat2sliderule.org/source/version
```

The only section in the documentation that I could find that mentions a netrc file is [this](http://icesat2sliderule.org/rtd/user_guide/NASA-Earthdata.html?highlight=netrc) but following those instructions did not fix the above error.

I also tried installing via pip in a fresh python 3.9 virtual environment, but that resulted in the same error. Am I missing something, or is this a bug?

**Comment by DonMaEn** [comment]
Also installing using `conda install -c conda-forge sliderule` in a fresh conda python 3.8.15 environment seems to give the same error.

**Comment by jpswinski** [comment]
@DonMaEn I'm sorry you ran into this trouble - this is an issue on our side.  We are in the middle of migrating SlideRule to an updated architecture and I dropped the ball on updating our website to reflect the changes.  Our new domain is slideruleearth.io, and the latest Python client has been updated to work with the new architecture.   We are preserving our old system for a few months until all of our existing users have migrated over, but I missed the case of new users coming to the old website and starting from there. (Very sorry!)

The links below are for the latest version of SlideRule:

Website: https://slideruleearth.io
Getting Started Guide: https://slideruleearth.io/rtd/getting_started/Getting-Started.html
First Request Tutorial: https://slideruleearth.io/rtd/tutorials/beginner/first_request.html

I have updated the old website to reflect the move so that hopefully others won't run into the same issues you did. 

If you have any further issues, please let me know.  We can keep this GitHub issue open until you are up and running so you can put any further issues you have here.

**Comment by DonMaEn** [comment]
@jpswinski Thanks for the quick response, and no worries.

Unfortunately I am still having issues using these new instructions. I tried installing slide rule using `conda install -c conda-forge sliderule` in a python 3.8.0 environment and I got stuck during the solving environment step of the conda install. Eventually I killed the process and tried again using a python 3.8.15 environment and that worked to install sliderule. However, after installing in the new environment, I encountered this error when following the getting started instructions on the new website:
```
>>> from sliderule import icesat2                                                                                                                                                                                  
>>>                                                                                                                                                                                                                
>>> # region of interest (2)                                                                                                                                                                                       
>>> grand_mesa = [ {"lon": -108.3435200747503, "lat": 38.89102961045247},                                                                                                                                          
...                {"lon": -107.7677425431139, "lat": 38.90611184543033},                                                                                                                                          
...                {"lon": -107.7818591266989, "lat": 39.26613714985466},                                                                                                                                          
...                {"lon": -108.3605610678553, "lat": 39.25086131372244},                                                                                                                                          
...                {"lon": -108.3435200747503, "lat": 38.89102961045247} ]                                                                                                                                         
>>>                                                                                                                                                                                                                
>>> # initialize (3)                                                                                                                                                                                               
>>> icesat2.init("slideruleearth.io")                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/dsm2588/.conda/envs/sliderule/lib/python3.8/site-packages/requests/models.py", line 971, in json                                                                                                     
    return complexjson.loads(self.text, **kwargs)                                                                                                                                                                  
  File "/home/dsm2588/.conda/envs/sliderule/lib/python3.8/json/__init__.py", line 357, in loads                                                                                                                    
    return _default_decoder.decode(s)                                                                                                                                                                              
  File "/home/dsm2588/.conda/envs/sliderule/lib/python3.8/json/decoder.py", line 337, in decode                                                                                                                    
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                                                                              
  File "/home/dsm2588/.conda/envs/sliderule/lib/python3.8/json/decoder.py", line 355, in raw_decode                                                                                                                
    raise JSONDecodeError("Expecting value", s, err.value) from None                                                                                                                                               
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                                                                                                                            
   
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dsm2588/.conda/envs/sliderule/lib/python3.8/site-packages/sliderule/icesat2.py", line 647, in init
    sliderule.set_url(url)
  File "/home/dsm2588/.conda/envs/sliderule/lib/python3.8/site-packages/sliderule/sliderule.py", line 484, in set_url
    update_available_servers()
  File "/home/dsm2588/.conda/envs/sliderule/lib/python3.8/site-packages/sliderule/sliderule.py", line 510, in update_available_servers
    response = requests.get(service_url, data='{"service":"sliderule"}', timeout=request_timeout).json()
  File "/home/dsm2588/.conda/envs/sliderule/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Next I am going to try the instructions on the First Request Tutorial page, I'll let you know if those work.

**Comment by DonMaEn** [comment]
It appears that the instructions in the "Making Your First Request" page are working for me. One of the steps threw a warning:
```
>>> icesat2.init("slideruleearth.io", verbose=True)                                                                                                                                                                
WARNING:sliderule.sliderule:Failed to retrieve username and password from netrc file: 'ps.slideruleearth.io'
```

Despite that warning, I was able to make the request from step 5 of the instructions just fine. I'm not sure why the conda forge install didn't work when the source install did work, but I think I have things working now. I will leave this issue open in case this is something the slidrule team wants to look into, but feel free to close it if you want.
